dataset_directory: '/home/dylan/datasets/answers/diabetes/'
output_directory: '/home/dylan/trained_model_files/sentence2vec/'
wordvec_dim: 300
model_name: 'test'
number_epochs: 100
batch_size: 64
learning_rate: 0.0001
weight_decay: 0.01
number_workers: 4
number_transformers: 2
number_attention_heads: 10
transformer_activation: 'tanh'
distance_metric: 'l1'
loss: 'margin'
margin: 0.5
