dataset_directory: '/home/dylan/datasets/answers/diabetes/'
output_directory: '/home/dylan/trained_model_files/sentence2vec/'
model_name: 'I300_R_T4_O32'
acceleration: False
wordvec_dim: 300
output_dim: 32
number_epochs: 500
batch_size: 64
learning_rate: 0.0001
weight_decay: 0.01
number_workers: 4
number_transformers: 4
number_attention_heads: 10
activation: 'tanh'
distance_metric: 'l1'
loss: 'ratio'
margin: 0.2
