dataset_directory: '/home/dylan/datasets/answers/diabetes/'
output_directory: '/tmp/'
model_name: 'test1'
model_file: null
number_epochs: 5
batch_size: 64
learning_rate: 0.0001
weight_decay: 0.01
number_workers: 1
embed_dimensionality: 512
conv_output_channels: 512
output_dimensionality: 128
output_activation: relu
margin: 0.2
p_norm: 2.0
normalize: True
