dataset_directory: '/home/dylan/datasets/answers/diabetes/'
output_directory: '/tmp/'
model_name: 'test'
model_file: null
number_epochs: 100
batch_size: 64
learning_rate: 0.0001
weight_decay: 0.01
number_workers: 4
embedding_type: 'glove.6B.300d'
embedding_dim: 300
number_transformers: 2
number_attention_heads: 10
transformer_activation: 'tanh'
distance_metric: 'l1'
output_process: 'normalize'
margin: 0.2
loss: 'margin'
