dataset_directory: '/home/dylan/datasets/answers/diabetes/'
output_directory: '/tmp/'
model_name: 'test1'
model_file: null
number_epochs: 50
batch_size: 64
learning_rate: 0.0001
weight_decay: 0.01
number_workers: 1
embed_dimensionality: 512
number_transformers: 6
transformer_activation: 'identity'
output_process: 'normalize'
distance_metric: 'l1'
margin: 0.2
loss: 'margin'
