dataset_directory: '/wheatley/dylan/datasets/answers_diabetes/'
output_directory: '/home/dylan/model_files/sentence2vec/'
model_name: 'softmax_tanh_l1'
model_file: null
number_epochs: 100
batch_size: 64
learning_rate: 0.0001
weight_decay: 0.01
number_workers: 4
embed_dimensionality: 512
number_transformers: 2
transformer_activation: 'tanh'
output_process: 'normalize'
distance_metric: 'l1'
margin: 0.2
loss: 'softmax'
